# Generated by Django 3.2.5 on 2021-07-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0002_remove_author_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(default='', help_text='Enter details here', max_length=400),
        ),
    ]
